//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAP_APIs.IVUZedasVehicles {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote", ConfigurationName="IVUZedasVehicles.VehicleWebFacade")]
    public interface VehicleWebFacade {
        
        // CODEGEN: Generating message contract since the operation importVehicles is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/mb/intf/vehicle/remote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CostCenter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vehicle))]
        SOAP_APIs.IVUZedasVehicles.importVehiclesResponse importVehicles(SOAP_APIs.IVUZedasVehicles.importVehicles request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestTypeField;
        
        private VehicleWithCostCenterRequest[] vehicleField;
        
        private VehicleGroup[] vehicleGroupField;
        
        private int protocolTransactionIdField;
        
        private bool protocolTransactionIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string requestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("requestType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicle", IsNullable=true, Order=1)]
        public VehicleWithCostCenterRequest[] vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
                this.RaisePropertyChanged("vehicle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicleGroup", IsNullable=true, Order=2)]
        public VehicleGroup[] vehicleGroup {
            get {
                return this.vehicleGroupField;
            }
            set {
                this.vehicleGroupField = value;
                this.RaisePropertyChanged("vehicleGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int protocolTransactionId {
            get {
                return this.protocolTransactionIdField;
            }
            set {
                this.protocolTransactionIdField = value;
                this.RaisePropertyChanged("protocolTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool protocolTransactionIdSpecified {
            get {
                return this.protocolTransactionIdFieldSpecified;
            }
            set {
                this.protocolTransactionIdFieldSpecified = value;
                this.RaisePropertyChanged("protocolTransactionIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleWithCostCenterRequest : Vehicle {
        
        private CostCenterRequest costCenterRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CostCenterRequest costCenterRequest {
            get {
                return this.costCenterRequestField;
            }
            set {
                this.costCenterRequestField = value;
                this.RaisePropertyChanged("costCenterRequest");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class CostCenterRequest : CostCenter {
        
        private string requestTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string requestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("requestType");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CostCenterRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class CostCenter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string abbreviationField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbreviation {
            get {
                return this.abbreviationField;
            }
            set {
                this.abbreviationField = value;
                this.RaisePropertyChanged("abbreviation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VehicleKeyResponse[] vehicleKeyResponsesField;
        
        private VehicleGroupKeyResponse[] vehicleGroupKeyResponsesField;
        
        private int protocolTransactionIdField;
        
        private bool protocolTransactionIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicleKeyResponses", IsNullable=true, Order=0)]
        public VehicleKeyResponse[] vehicleKeyResponses {
            get {
                return this.vehicleKeyResponsesField;
            }
            set {
                this.vehicleKeyResponsesField = value;
                this.RaisePropertyChanged("vehicleKeyResponses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicleGroupKeyResponses", IsNullable=true, Order=1)]
        public VehicleGroupKeyResponse[] vehicleGroupKeyResponses {
            get {
                return this.vehicleGroupKeyResponsesField;
            }
            set {
                this.vehicleGroupKeyResponsesField = value;
                this.RaisePropertyChanged("vehicleGroupKeyResponses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int protocolTransactionId {
            get {
                return this.protocolTransactionIdField;
            }
            set {
                this.protocolTransactionIdField = value;
                this.RaisePropertyChanged("protocolTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool protocolTransactionIdSpecified {
            get {
                return this.protocolTransactionIdFieldSpecified;
            }
            set {
                this.protocolTransactionIdFieldSpecified = value;
                this.RaisePropertyChanged("protocolTransactionIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleKeyResponse : VehicleKey {
        
        private ProtocolEntry[] protocolEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("protocolEntry", IsNullable=true, Order=0)]
        public ProtocolEntry[] protocolEntry {
            get {
                return this.protocolEntryField;
            }
            set {
                this.protocolEntryField = value;
                this.RaisePropertyChanged("protocolEntry");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class ProtocolEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehicleKeyResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string divisionAbbreviationField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string divisionAbbreviation {
            get {
                return this.divisionAbbreviationField;
            }
            set {
                this.divisionAbbreviationField = value;
                this.RaisePropertyChanged("divisionAbbreviation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleGroupKeyResponse : VehicleGroupKey {
        
        private ProtocolEntry[] protocolEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("protocolEntry", IsNullable=true, Order=0)]
        public ProtocolEntry[] protocolEntry {
            get {
                return this.protocolEntryField;
            }
            set {
                this.protocolEntryField = value;
                this.RaisePropertyChanged("protocolEntry");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehicleGroupKeyResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleGroupKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string abbreviationField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbreviation {
            get {
                return this.abbreviationField;
            }
            set {
                this.abbreviationField = value;
                this.RaisePropertyChanged("abbreviation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleGroupPart : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VehicleKey vehicleKeyField;
        
        private int positionField;
        
        private string orientationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleKey vehicleKey {
            get {
                return this.vehicleKeyField;
            }
            set {
                this.vehicleKeyField = value;
                this.RaisePropertyChanged("vehicleKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string orientation {
            get {
                return this.orientationField;
            }
            set {
                this.orientationField = value;
                this.RaisePropertyChanged("orientation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VehicleGroupKey vehicleGroupKeyField;
        
        private string vehicleGroupTypeField;
        
        private VehicleGroupPart[] vehicleGroupPartField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleGroupKey vehicleGroupKey {
            get {
                return this.vehicleGroupKeyField;
            }
            set {
                this.vehicleGroupKeyField = value;
                this.RaisePropertyChanged("vehicleGroupKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string vehicleGroupType {
            get {
                return this.vehicleGroupTypeField;
            }
            set {
                this.vehicleGroupTypeField = value;
                this.RaisePropertyChanged("vehicleGroupType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicleGroupPart", IsNullable=true, Order=2)]
        public VehicleGroupPart[] vehicleGroupPart {
            get {
                return this.vehicleGroupPartField;
            }
            set {
                this.vehicleGroupPartField = value;
                this.RaisePropertyChanged("vehicleGroupPart");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class BrakeSystem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string brakeTypeField;
        
        private int brakeWeightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string brakeType {
            get {
                return this.brakeTypeField;
            }
            set {
                this.brakeTypeField = value;
                this.RaisePropertyChanged("brakeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int brakeWeight {
            get {
                return this.brakeWeightField;
            }
            set {
                this.brakeWeightField = value;
                this.RaisePropertyChanged("brakeWeight");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class RegistrationDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class DueDateAccountComponent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dueDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
                this.RaisePropertyChanged("dueDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class ServiceIntervalAccountComponent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string typeField;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class ServiceIntervalAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string abbreviationField;
        
        private string datetimeField;
        
        private string effectiveFromField;
        
        private ServiceIntervalAccountComponent serviceIntervalAccountComponentField;
        
        private DueDateAccountComponent dueDateAccountComponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbreviation {
            get {
                return this.abbreviationField;
            }
            set {
                this.abbreviationField = value;
                this.RaisePropertyChanged("abbreviation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string datetime {
            get {
                return this.datetimeField;
            }
            set {
                this.datetimeField = value;
                this.RaisePropertyChanged("datetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string effectiveFrom {
            get {
                return this.effectiveFromField;
            }
            set {
                this.effectiveFromField = value;
                this.RaisePropertyChanged("effectiveFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ServiceIntervalAccountComponent serviceIntervalAccountComponent {
            get {
                return this.serviceIntervalAccountComponentField;
            }
            set {
                this.serviceIntervalAccountComponentField = value;
                this.RaisePropertyChanged("serviceIntervalAccountComponent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public DueDateAccountComponent dueDateAccountComponent {
            get {
                return this.dueDateAccountComponentField;
            }
            set {
                this.dueDateAccountComponentField = value;
                this.RaisePropertyChanged("dueDateAccountComponent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class DynamicAttribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class OutOfServiceDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehicleWithCostCenterRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class Vehicle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VehicleKey vehicleKeyField;
        
        private string externalNumberField;
        
        private string vehicleTypeAbbreviationField;
        
        private string depotAbbreviationField;
        
        private string descriptionField;
        
        private string registrationNumberField;
        
        private string advertisingField;
        
        private OutOfServiceDate takenOutOfServiceDateField;
        
        private bool countingVehicleField;
        
        private bool countingVehicleFieldSpecified;
        
        private string[] allowedMovingDirectionsField;
        
        private DynamicAttribute[] dynamicAttributesField;
        
        private ServiceIntervalAccount[] serviceIntervalAccountField;
        
        private int lengthField;
        
        private bool lengthFieldSpecified;
        
        private int weightField;
        
        private bool weightFieldSpecified;
        
        private RegistrationDate registrationDateField;
        
        private string[] trainControlSystemsField;
        
        private bool tiltingFunctionField;
        
        private bool tiltingFunctionFieldSpecified;
        
        private int maxSpeedField;
        
        private bool maxSpeedFieldSpecified;
        
        private BrakeSystem[] brakeSystemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleKey vehicleKey {
            get {
                return this.vehicleKeyField;
            }
            set {
                this.vehicleKeyField = value;
                this.RaisePropertyChanged("vehicleKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string externalNumber {
            get {
                return this.externalNumberField;
            }
            set {
                this.externalNumberField = value;
                this.RaisePropertyChanged("externalNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string vehicleTypeAbbreviation {
            get {
                return this.vehicleTypeAbbreviationField;
            }
            set {
                this.vehicleTypeAbbreviationField = value;
                this.RaisePropertyChanged("vehicleTypeAbbreviation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string depotAbbreviation {
            get {
                return this.depotAbbreviationField;
            }
            set {
                this.depotAbbreviationField = value;
                this.RaisePropertyChanged("depotAbbreviation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string registrationNumber {
            get {
                return this.registrationNumberField;
            }
            set {
                this.registrationNumberField = value;
                this.RaisePropertyChanged("registrationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string advertising {
            get {
                return this.advertisingField;
            }
            set {
                this.advertisingField = value;
                this.RaisePropertyChanged("advertising");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public OutOfServiceDate takenOutOfServiceDate {
            get {
                return this.takenOutOfServiceDateField;
            }
            set {
                this.takenOutOfServiceDateField = value;
                this.RaisePropertyChanged("takenOutOfServiceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool countingVehicle {
            get {
                return this.countingVehicleField;
            }
            set {
                this.countingVehicleField = value;
                this.RaisePropertyChanged("countingVehicle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countingVehicleSpecified {
            get {
                return this.countingVehicleFieldSpecified;
            }
            set {
                this.countingVehicleFieldSpecified = value;
                this.RaisePropertyChanged("countingVehicleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("allowedMovingDirections", IsNullable=true, Order=9)]
        public string[] allowedMovingDirections {
            get {
                return this.allowedMovingDirectionsField;
            }
            set {
                this.allowedMovingDirectionsField = value;
                this.RaisePropertyChanged("allowedMovingDirections");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dynamicAttributes", IsNullable=true, Order=10)]
        public DynamicAttribute[] dynamicAttributes {
            get {
                return this.dynamicAttributesField;
            }
            set {
                this.dynamicAttributesField = value;
                this.RaisePropertyChanged("dynamicAttributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceIntervalAccount", IsNullable=true, Order=11)]
        public ServiceIntervalAccount[] serviceIntervalAccount {
            get {
                return this.serviceIntervalAccountField;
            }
            set {
                this.serviceIntervalAccountField = value;
                this.RaisePropertyChanged("serviceIntervalAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
                this.RaisePropertyChanged("lengthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool weightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
                this.RaisePropertyChanged("weightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public RegistrationDate registrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
                this.RaisePropertyChanged("registrationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("trainControlSystem")]
        public string[] trainControlSystems {
            get {
                return this.trainControlSystemsField;
            }
            set {
                this.trainControlSystemsField = value;
                this.RaisePropertyChanged("trainControlSystems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool tiltingFunction {
            get {
                return this.tiltingFunctionField;
            }
            set {
                this.tiltingFunctionField = value;
                this.RaisePropertyChanged("tiltingFunction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tiltingFunctionSpecified {
            get {
                return this.tiltingFunctionFieldSpecified;
            }
            set {
                this.tiltingFunctionFieldSpecified = value;
                this.RaisePropertyChanged("tiltingFunctionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int maxSpeed {
            get {
                return this.maxSpeedField;
            }
            set {
                this.maxSpeedField = value;
                this.RaisePropertyChanged("maxSpeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxSpeedSpecified {
            get {
                return this.maxSpeedFieldSpecified;
            }
            set {
                this.maxSpeedFieldSpecified = value;
                this.RaisePropertyChanged("maxSpeedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute("brakeSystem")]
        public BrakeSystem[] brakeSystems {
            get {
                return this.brakeSystemsField;
            }
            set {
                this.brakeSystemsField = value;
                this.RaisePropertyChanged("brakeSystems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importVehicles {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote", Order=0)]
        public SOAP_APIs.IVUZedasVehicles.VehicleRequest vehicleRequest;
        
        public importVehicles() {
        }
        
        public importVehicles(SOAP_APIs.IVUZedasVehicles.VehicleRequest vehicleRequest) {
            this.vehicleRequest = vehicleRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importVehiclesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote", Order=0)]
        public SOAP_APIs.IVUZedasVehicles.VehicleResponse vehicleResponse;
        
        public importVehiclesResponse() {
        }
        
        public importVehiclesResponse(SOAP_APIs.IVUZedasVehicles.VehicleResponse vehicleResponse) {
            this.vehicleResponse = vehicleResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VehicleWebFacadeChannel : SOAP_APIs.IVUZedasVehicles.VehicleWebFacade, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehicleWebFacadeClient : System.ServiceModel.ClientBase<SOAP_APIs.IVUZedasVehicles.VehicleWebFacade>, SOAP_APIs.IVUZedasVehicles.VehicleWebFacade {
        
        public VehicleWebFacadeClient() {
        }
        
        public VehicleWebFacadeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehicleWebFacadeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleWebFacadeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleWebFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP_APIs.IVUZedasVehicles.importVehiclesResponse SOAP_APIs.IVUZedasVehicles.VehicleWebFacade.importVehicles(SOAP_APIs.IVUZedasVehicles.importVehicles request) {
            return base.Channel.importVehicles(request);
        }
        
        public SOAP_APIs.IVUZedasVehicles.VehicleResponse importVehicles(SOAP_APIs.IVUZedasVehicles.VehicleRequest vehicleRequest) {
            SOAP_APIs.IVUZedasVehicles.importVehicles inValue = new SOAP_APIs.IVUZedasVehicles.importVehicles();
            inValue.vehicleRequest = vehicleRequest;
            SOAP_APIs.IVUZedasVehicles.importVehiclesResponse retVal = ((SOAP_APIs.IVUZedasVehicles.VehicleWebFacade)(this)).importVehicles(inValue);
            return retVal.vehicleResponse;
        }
    }
}
