//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAP_APIs.IVUZedas {


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", ConfigurationName = "IVUZedas.DeploymentRestrictionServicePortType")]
    public interface OnxDeploymentRestrictionServicePortType
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0/createDeploymentRestr" +
            "iction", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        SOAP_APIs.IVUZedas.createDeploymentRestrictionResponse createDeploymentRestriction(SOAP_APIs.IVUZedas.createDeploymentRestrictionRequest request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        //  [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0/createDeploymentRestr" +
        //    "iction", ReplyAction="*")]
        // System.Threading.Tasks.Task<SOAP_APIs.IVUZedas.createDeploymentRestrictionResponse> createDeploymentRestrictionAsync(SOAP_APIs.IVUZedas.createDeploymentRestrictionRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0/modifyDeploymentRestr" +
            "iction", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        SOAP_APIs.IVUZedas.modifyDeploymentRestrictionResponse modifyDeploymentRestriction(SOAP_APIs.IVUZedas.modifyDeploymentRestrictionRequest request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        //[System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0/modifyDeploymentRestr" +
        //  "iction", ReplyAction="*")]
        // System.Threading.Tasks.Task<SOAP_APIs.IVUZedas.modifyDeploymentRestrictionResponse> modifyDeploymentRestrictionAsync(SOAP_APIs.IVUZedas.modifyDeploymentRestrictionRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0/deleteDeploymentRestr" +
            "iction", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        SOAP_APIs.IVUZedas.deleteDeploymentRestrictionResponse deleteDeploymentRestriction(SOAP_APIs.IVUZedas.deleteDeploymentRestrictionRequest request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        // [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0/deleteDeploymentRestr" +
        //   "iction", ReplyAction="*")]
        // System.Threading.Tasks.Task<SOAP_APIs.IVUZedas.deleteDeploymentRestrictionResponse> deleteDeploymentRestrictionAsync(SOAP_APIs.IVUZedas.deleteDeploymentRestrictionRequest request);
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", ConfigurationName="IVUZedas.DeploymentRestrictionServicePortType")]
    public interface DeploymentRestrictionServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0/createDeploymentRestr" +
            "iction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOAP_APIs.IVUZedas.createDeploymentRestrictionResponse createDeploymentRestriction(SOAP_APIs.IVUZedas.createDeploymentRestrictionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
       [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0/createDeploymentRestr" +
            "iction", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP_APIs.IVUZedas.createDeploymentRestrictionResponse> createDeploymentRestrictionAsync(SOAP_APIs.IVUZedas.createDeploymentRestrictionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0/modifyDeploymentRestr" +
            "iction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOAP_APIs.IVUZedas.modifyDeploymentRestrictionResponse modifyDeploymentRestriction(SOAP_APIs.IVUZedas.modifyDeploymentRestrictionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
       [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0/modifyDeploymentRestr" +
            "iction", ReplyAction="*")]
       System.Threading.Tasks.Task<SOAP_APIs.IVUZedas.modifyDeploymentRestrictionResponse> modifyDeploymentRestrictionAsync(SOAP_APIs.IVUZedas.modifyDeploymentRestrictionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0/deleteDeploymentRestr" +
            "iction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOAP_APIs.IVUZedas.deleteDeploymentRestrictionResponse deleteDeploymentRestriction(SOAP_APIs.IVUZedas.deleteDeploymentRestrictionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0/deleteDeploymentRestr" +
            "iction", ReplyAction="*")]
         System.Threading.Tasks.Task<SOAP_APIs.IVUZedas.deleteDeploymentRestrictionResponse> deleteDeploymentRestrictionAsync(SOAP_APIs.IVUZedas.deleteDeploymentRestrictionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0")]
    public partial class DateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int yearField;
        
        private int monthField;
        
        private int dayField;
        
        private int hourField;
        
        private int minuteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
                this.RaisePropertyChanged("day");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int hour {
            get {
                return this.hourField;
            }
            set {
                this.hourField = value;
                this.RaisePropertyChanged("hour");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int minute {
            get {
                return this.minuteField;
            }
            set {
                this.minuteField = value;
                this.RaisePropertyChanged("minute");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDeploymentRestriction", WrapperNamespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", IsWrapped=true)]
    public partial class createDeploymentRestrictionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string division;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vehicle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SOAP_APIs.IVUZedas.DateTime startTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SOAP_APIs.IVUZedas.DateTime endTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string comment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serializedKey;
        
        public createDeploymentRestrictionRequest() {
        }
        
        public createDeploymentRestrictionRequest(string division, string vehicle, SOAP_APIs.IVUZedas.DateTime startTime, SOAP_APIs.IVUZedas.DateTime endTime, string reason, string comment, string user, string serializedKey) {
            this.division = division;
            this.vehicle = vehicle;
            this.startTime = startTime;
            this.endTime = endTime;
            this.reason = reason;
            this.comment = comment;
            this.user = user;
            this.serializedKey = serializedKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDeploymentRestrictionResponse", WrapperNamespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", IsWrapped=true)]
    public partial class createDeploymentRestrictionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text;
        
        public createDeploymentRestrictionResponse() {
        }
        
        public createDeploymentRestrictionResponse(int code, string text) {
            this.code = code;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifyDeploymentRestriction", WrapperNamespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", IsWrapped=true)]
    public partial class modifyDeploymentRestrictionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string division;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vehicle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SOAP_APIs.IVUZedas.DateTime startTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SOAP_APIs.IVUZedas.DateTime endTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string comment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serializedKey;
        
        public modifyDeploymentRestrictionRequest() {
        }
        
        public modifyDeploymentRestrictionRequest(string division, string vehicle, SOAP_APIs.IVUZedas.DateTime startTime, SOAP_APIs.IVUZedas.DateTime endTime, string reason, string comment, string user, string serializedKey) {
            this.division = division;
            this.vehicle = vehicle;
            this.startTime = startTime;
            this.endTime = endTime;
            this.reason = reason;
            this.comment = comment;
            this.user = user;
            this.serializedKey = serializedKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifyDeploymentRestrictionResponse", WrapperNamespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", IsWrapped=true)]
    public partial class modifyDeploymentRestrictionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text;
        
        public modifyDeploymentRestrictionResponse() {
        }
        
        public modifyDeploymentRestrictionResponse(int code, string text) {
            this.code = code;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteDeploymentRestriction", WrapperNamespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", IsWrapped=true)]
    public partial class deleteDeploymentRestrictionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string division;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vehicle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SOAP_APIs.IVUZedas.DateTime startTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SOAP_APIs.IVUZedas.DateTime endTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string comment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serializedKey;
        
        public deleteDeploymentRestrictionRequest() {
        }
        
        public deleteDeploymentRestrictionRequest(string division, string vehicle, SOAP_APIs.IVUZedas.DateTime startTime, SOAP_APIs.IVUZedas.DateTime endTime, string reason, string comment, string user, string serializedKey) {
            this.division = division;
            this.vehicle = vehicle;
            this.startTime = startTime;
            this.endTime = endTime;
            this.reason = reason;
            this.comment = comment;
            this.user = user;
            this.serializedKey = serializedKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteDeploymentRestrictionResponse", WrapperNamespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", IsWrapped=true)]
    public partial class deleteDeploymentRestrictionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/MICROBUS/DeploymentRestrictionService/1.0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text;
        
        public deleteDeploymentRestrictionResponse() {
        }
        
        public deleteDeploymentRestrictionResponse(int code, string text) {
            this.code = code;
            this.text = text;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeploymentRestrictionServicePortTypeChannel : SOAP_APIs.IVUZedas.DeploymentRestrictionServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeploymentRestrictionServicePortTypeClient : System.ServiceModel.ClientBase<SOAP_APIs.IVUZedas.DeploymentRestrictionServicePortType>, SOAP_APIs.IVUZedas.DeploymentRestrictionServicePortType {
        
        public DeploymentRestrictionServicePortTypeClient() {
        }
        
        public DeploymentRestrictionServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeploymentRestrictionServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeploymentRestrictionServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeploymentRestrictionServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP_APIs.IVUZedas.createDeploymentRestrictionResponse SOAP_APIs.IVUZedas.DeploymentRestrictionServicePortType.createDeploymentRestriction(SOAP_APIs.IVUZedas.createDeploymentRestrictionRequest request) {
            return base.Channel.createDeploymentRestriction(request);
        }
        
        public int createDeploymentRestriction(string division, string vehicle, SOAP_APIs.IVUZedas.DateTime startTime, SOAP_APIs.IVUZedas.DateTime endTime, string reason, string comment, string user, string serializedKey, out string text) {
            SOAP_APIs.IVUZedas.createDeploymentRestrictionRequest inValue = new SOAP_APIs.IVUZedas.createDeploymentRestrictionRequest();
            inValue.division = division;
            inValue.vehicle = vehicle;
            inValue.startTime = startTime;
            inValue.endTime = endTime;
            inValue.reason = reason;
            inValue.comment = comment;
            inValue.user = user;
            inValue.serializedKey = serializedKey;
            SOAP_APIs.IVUZedas.createDeploymentRestrictionResponse retVal = ((SOAP_APIs.IVUZedas.DeploymentRestrictionServicePortType)(this)).createDeploymentRestriction(inValue);
            text = retVal.text;
            return retVal.code;
        }
        
        public System.Threading.Tasks.Task<SOAP_APIs.IVUZedas.createDeploymentRestrictionResponse> createDeploymentRestrictionAsync(SOAP_APIs.IVUZedas.createDeploymentRestrictionRequest request) {
            return base.Channel.createDeploymentRestrictionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP_APIs.IVUZedas.modifyDeploymentRestrictionResponse SOAP_APIs.IVUZedas.DeploymentRestrictionServicePortType.modifyDeploymentRestriction(SOAP_APIs.IVUZedas.modifyDeploymentRestrictionRequest request) {
            return base.Channel.modifyDeploymentRestriction(request);
        }
        
        public int modifyDeploymentRestriction(string division, string vehicle, SOAP_APIs.IVUZedas.DateTime startTime, SOAP_APIs.IVUZedas.DateTime endTime, string reason, string comment, string user, string serializedKey, out string text) {
            SOAP_APIs.IVUZedas.modifyDeploymentRestrictionRequest inValue = new SOAP_APIs.IVUZedas.modifyDeploymentRestrictionRequest();
            inValue.division = division;
            inValue.vehicle = vehicle;
            inValue.startTime = startTime;
            inValue.endTime = endTime;
            inValue.reason = reason;
            inValue.comment = comment;
            inValue.user = user;
            inValue.serializedKey = serializedKey;
            SOAP_APIs.IVUZedas.modifyDeploymentRestrictionResponse retVal = ((SOAP_APIs.IVUZedas.DeploymentRestrictionServicePortType)(this)).modifyDeploymentRestriction(inValue);
            text = retVal.text;
            return retVal.code;
        }
        
        public System.Threading.Tasks.Task<SOAP_APIs.IVUZedas.modifyDeploymentRestrictionResponse> modifyDeploymentRestrictionAsync(SOAP_APIs.IVUZedas.modifyDeploymentRestrictionRequest request) {
            return base.Channel.modifyDeploymentRestrictionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP_APIs.IVUZedas.deleteDeploymentRestrictionResponse SOAP_APIs.IVUZedas.DeploymentRestrictionServicePortType.deleteDeploymentRestriction(SOAP_APIs.IVUZedas.deleteDeploymentRestrictionRequest request) {
            return base.Channel.deleteDeploymentRestriction(request);
        }
        
        public int deleteDeploymentRestriction(string division, string vehicle, SOAP_APIs.IVUZedas.DateTime startTime, SOAP_APIs.IVUZedas.DateTime endTime, string reason, string comment, string user, string serializedKey, out string text) {
            SOAP_APIs.IVUZedas.deleteDeploymentRestrictionRequest inValue = new SOAP_APIs.IVUZedas.deleteDeploymentRestrictionRequest();
            inValue.division = division;
            inValue.vehicle = vehicle;
            inValue.startTime = startTime;
            inValue.endTime = endTime;
            inValue.reason = reason;
            inValue.comment = comment;
            inValue.user = user;
            inValue.serializedKey = serializedKey;
            SOAP_APIs.IVUZedas.deleteDeploymentRestrictionResponse retVal = ((SOAP_APIs.IVUZedas.DeploymentRestrictionServicePortType)(this)).deleteDeploymentRestriction(inValue);
            text = retVal.text;
            return retVal.code;
        }
        
        public System.Threading.Tasks.Task<SOAP_APIs.IVUZedas.deleteDeploymentRestrictionResponse> deleteDeploymentRestrictionAsync(SOAP_APIs.IVUZedas.deleteDeploymentRestrictionRequest request) {
            return base.Channel.deleteDeploymentRestrictionAsync(request);
        }
    }
}
