//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAP_APIs.IVUVehicleConsist {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intf.mb.ivu.de/", ConfigurationName="IVUVehicleConsist.IntfJobsPushPortType")]
    public interface IntfJobsPushPortType {
        
        // CODEGEN: Generating message contract since the operation sendIntfJobsExport is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ivu.de/intf.jobs.impl/IntfJobsPushWebService/IntfJobsSendExport")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void sendIntfJobsExport(SOAP_APIs.IVUVehicleConsist.sendIntfJobsExport request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/integration/vehicle/vehiclegroup/standard")]
    public partial class VehicleGroupExport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VehicleGroup[] vehicleGroupsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("vehicleGroup", IsNullable=false)]
        public VehicleGroup[] vehicleGroups {
            get {
                return this.vehicleGroupsField;
            }
            set {
                this.vehicleGroupsField = value;
                this.RaisePropertyChanged("vehicleGroups");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/integration/vehicle/vehiclegroup/standard")]
    public partial class VehicleGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VehicleGroupKey vehicleGroupKeyField;
        
        private string vehicleGroupTypeField;
        
        private VehicleGroupPart[] vehicleGroupPartField;
        
        private string validFromField;
        
        private bool existsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleGroupKey vehicleGroupKey {
            get {
                return this.vehicleGroupKeyField;
            }
            set {
                this.vehicleGroupKeyField = value;
                this.RaisePropertyChanged("vehicleGroupKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string vehicleGroupType {
            get {
                return this.vehicleGroupTypeField;
            }
            set {
                this.vehicleGroupTypeField = value;
                this.RaisePropertyChanged("vehicleGroupType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicleGroupPart", Order=2)]
        public VehicleGroupPart[] vehicleGroupPart {
            get {
                return this.vehicleGroupPartField;
            }
            set {
                this.vehicleGroupPartField = value;
                this.RaisePropertyChanged("vehicleGroupPart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string validFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
                this.RaisePropertyChanged("validFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
                this.RaisePropertyChanged("exists");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/integration/vehicle/vehiclegroup/standard")]
    public partial class VehicleGroupKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string abbreviationField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbreviation {
            get {
                return this.abbreviationField;
            }
            set {
                this.abbreviationField = value;
                this.RaisePropertyChanged("abbreviation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/integration/vehicle/vehiclegroup/standard")]
    public partial class VehicleKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberField;
        
        private string externalNumberField;
        
        private string divisionAbbreviationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string externalNumber {
            get {
                return this.externalNumberField;
            }
            set {
                this.externalNumberField = value;
                this.RaisePropertyChanged("externalNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string divisionAbbreviation {
            get {
                return this.divisionAbbreviationField;
            }
            set {
                this.divisionAbbreviationField = value;
                this.RaisePropertyChanged("divisionAbbreviation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/integration/vehicle/vehiclegroup/standard")]
    public partial class VehicleGroupPart : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VehicleKey vehicleKeyField;
        
        private string positionField;
        
        private string orientationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleKey vehicleKey {
            get {
                return this.vehicleKeyField;
            }
            set {
                this.vehicleKeyField = value;
                this.RaisePropertyChanged("vehicleKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string orientation {
            get {
                return this.orientationField;
            }
            set {
                this.orientationField = value;
                this.RaisePropertyChanged("orientation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendIntfJobsExport {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/integration/vehicle/vehiclegroup/standard", Order=0)]
        public SOAP_APIs.IVUVehicleConsist.VehicleGroupExport vehicleGroupExport;
        
        public sendIntfJobsExport() {
        }
        
        public sendIntfJobsExport(SOAP_APIs.IVUVehicleConsist.VehicleGroupExport vehicleGroupExport) {
            this.vehicleGroupExport = vehicleGroupExport;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntfJobsPushPortTypeChannel : SOAP_APIs.IVUVehicleConsist.IntfJobsPushPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntfJobsPushPortTypeClient : System.ServiceModel.ClientBase<SOAP_APIs.IVUVehicleConsist.IntfJobsPushPortType>, SOAP_APIs.IVUVehicleConsist.IntfJobsPushPortType {
        
        public IntfJobsPushPortTypeClient() {
        }
        
        public IntfJobsPushPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntfJobsPushPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntfJobsPushPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntfJobsPushPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SOAP_APIs.IVUVehicleConsist.IntfJobsPushPortType.sendIntfJobsExport(SOAP_APIs.IVUVehicleConsist.sendIntfJobsExport request) {
            base.Channel.sendIntfJobsExport(request);
        }
        
        public void sendIntfJobsExport(SOAP_APIs.IVUVehicleConsist.VehicleGroupExport vehicleGroupExport) {
            SOAP_APIs.IVUVehicleConsist.sendIntfJobsExport inValue = new SOAP_APIs.IVUVehicleConsist.sendIntfJobsExport();
            inValue.vehicleGroupExport = vehicleGroupExport;
            ((SOAP_APIs.IVUVehicleConsist.IntfJobsPushPortType)(this)).sendIntfJobsExport(inValue);
        }
    }
}

