# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

     # - name: Setup NuGet
     #   uses: NuGet/setup-nuget@v1.0.5
      -  run: echo "folder ${{github.workspace}}"
      - name: List files in the repository
        run: |
          dir
      - name: Restore Packages
        run: nuget restore ./SOAP_APIs/SOAP_APIs.csproj -PackagesDirectory .\packages
      -  run: echo "folder ${{github.workspace}}"
      - name: List files in the repository
        #working-directory: SOAP_APIs
        run: |
          dir
      

      - name: Build Solution
        run: |
          msbuild.exe ./SOAP_APIs/SOAP_APIs.csproj /p:Configuration=Release /p:Platform=AnyCPU /p:PublishDir= ./build
      - name: List files in the repository
        run: |
          dir
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Bundle
          path: "./_build"

