name: Appconfig

on:
  workflow_dispatch:

env:
  AZURE_SOAPAPI_NAME: 'as-onx1-intgapp-dev-001'   # set this to your function app name on Azure
  AZURE_SOAPAPI_PACKAGE_PATH: 'SOAP_APIs'       
  MY_FILE_PATH: 'D:\BuildSoap\BuildSoap\SAOAP_APIS\appsettings.json'    # set this to the dotnet version to use (e.g.'6.0.x', 8.0.x)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: write
      id-token: write
      
    steps:
    -  run: echo "folder ${{github.workspace}}"

    - run: echo "::set-output name=appsettings_json::$(tr -d '\n' < ${{ env.MY_FILE_PATH }})"
      id: load-json
        
    #- name: Config
    #  uses: azure/appservice-settings@v1
    #  with:
    #    app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
    #    app-settings-json: '${{ steps.load-json.outputs.appsettings_json }}' 
    #    id: settings
        
    
 
